Application:
  Title: gravity
  Description: Gravity is an open-source alternative for blogs, allowing for easy page configuration and ultimate flexibility.
  Link: github.com/prplwtf/gravity

Connections:
  GitHub:
  YouTube:
  Twitter: