Application:
  Title: "gravity"
  Description: "I write posts about anything that comes to mind. My gravity blog is just a place where my thoughts can walk around freely without bumping in to someone or something."
  Link: "github.com/prplwtf/gravity"

Connections:
  GitHub: "prplwtf"
  YouTube: "prplwtf"
  Twitter: "prplwtf"